export const configs = {
  NODE_ENV: process.env.NODE_ENV,
  MONGO_URI: process.env.MONGO_URI,
  MAIL_HOST: process.env.MAIL_HOST,
  MAIL_PORT: process.env.MAIL_PORT as unknown as number,
  MAIL_USER: process.env.MAIL_USER,
  MAIL_PASSWORD: process.env.MAIL_PASSWORD,
  MAIL_SENDER: process.env.MAIL_SENDER,
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
  DEFAULT_USER_PASSWORD: process.env.DEFAULT_USER_PASSWORD,
  OTP_ENCODING: process.env.OTP_ENCODING,
  OTP_STEP: process.env.OTP_STEP,
  OTP_WINDOW: process.env.OTP_WINDOW,
  Backend_url: process.env.Backend_url,
};
